"""added blacklist

Revision ID: 80948048efa2
Revises: 323f3aae49b6
Create Date: 2021-10-06 15:41:50.821047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80948048efa2'
down_revision = '323f3aae49b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
